### ISSUE TITLE
Standardize dealing with illegal arguments.

### ISSUE THREAD

**Issue by Olilin1** [mebn/DD2480#76]
Currently there is no standard for dealing with illegal arguments. Some of the LIC functions return false if arguments are illegal. Some return false, and some just assume the arguments are legal.

To remedy this, each LIC function should check that the arguments are within the bounds specified by the program specification, and throw an IllegalArgumentException if arguments are not legal.

**Comment by dj-sourbrough** [comment]
We will need to refactor all tests which check the bounds of arguments as well
